### ISSUE TITLE
Norm (!) 

### ISSUE THREAD

**Issue by NigelMDR** [ece-231l-fall-2019/week-4-complex-nigelteam#2]
#### Currently not passing Test using the built in std::complex. 
<b/>
Note: It does pass using Complex.h

https://github.com/ece-231l-fall-2019/week-4-complex-nigelteam/blob/f9523a3c2717c58db500d17b1a604c0b5ce74faf/runtests.cpp#L100

https://github.com/ece-231l-fall-2019/week-4-complex-nigelteam/blob/f9523a3c2717c58db500d17b1a604c0b5ce74faf/runtests.cpp#L99

https://github.com/ece-231l-fall-2019/week-4-complex-nigelteam/blob/f9523a3c2717c58db500d17b1a604c0b5ce74faf/runtests.cpp#L101

Delete when done, please. (cout)

**Comment by micrometz** [comment]
done
